### ISSUE TITLE
Doco and package name

### ISSUE THREAD

**Issue by RichardAH** [XRPLF/xrpl4j#1]
Hey guys 
Really nice work on this library
Few small things:
- Package names should be `org.xrplf.*` not `com.ripple.*`
- Some (maybe all?) readmes contain broken links, e.g. the links in this one: https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-keypairs/README.md
- Readmes in each package should probably have at least one sample/example usage if not more

**Comment by nkramer44** [comment]
@RichardAH I think we are going with `org.xrpl` for the package names.  

I fixed the broken links in READMEs, and I have it in my backlog to improve documentation overall.  Right now we're mainly focused on getting something released so that people internal to Ripple can start playing with the library.

Here is the PR https://github.com/XRPLF/xrpl4j/pull/3

**Comment by sappenin** [comment]
This is complete. Plz reopen if there are still issues or changes that you see (note that the library is WIP, still a lot of cleanup todo, coming this week).
