### ISSUE TITLE
XRP Wallet only works with 16 byte seed

### ISSUE THREAD

**Issue by manthanhd** [XRPLF/xrpl4j#101]
I'm using xrpl4j to generate xrp wallet as part of a HD wallet. I am able to generate the wallet fine when the seed size is 16 bytes (128 bits / 12 word mnemonic) but when the seed size is 32 (256 bits / 24 word mnemonic) it fails. The current workaround I have is to strip the seed of the bytes in excess of 16.

See HD wallet generation using bitcoin4j code [here](https://github.com/key-connect/services/blob/9033c1943a759da97be30ed911154b0291dfb2d8/keyconnect-sdk/src/main/java/app/keyconnect/sdk/wallets/DeterministicWallet.java#L38).

```java
new DeterministicSeed(
        new SecureRandom(),
        256,
        Optional.ofNullable(passphrase).orElse("")
    );
```

See stripping of bytes in excess of 16 workaround [here](https://github.com/key-connect/services/blob/9033c1943a759da97be30ed911154b0291dfb2d8/keyconnect-sdk/src/main/java/app/keyconnect/sdk/wallets/XrpWallet.java#L106).

```java
ArrayUtils.subarray(privKey.toByteArray(), 0, 16);
```

While this is functional, it strips the entropy and is restrictively less secure.

Requirement:
- XRP Wallet should allow seed length greater than and equal to current length of 16 bytes for more secure wallets

**Comment by sappenin** [comment]
Leaving some notes for posterity -- still thinking this through. 

For ed25519 keys just using the 32-bytes as the private-key is one option. For secp256k1, using sha512Half(24 words) seems like it should be fine.

1. "_The security level of secp256k1 and Ed25519 is around 128 bits. Note that just because our standard derivation of the private key is from a 16 byte seed doesn’t mean that’s how others have to do it._"
1. "_For Ed25519, you can basically use any 32 bytes directly as a private key. For secp256k1 it’s slightly trickier: the key must be less than the curve’s order._"

Also, see here: https://feedback.xumm.dev/xumm/p/raw-private-key-64-bit-support for interesting reading.

**Comment by nkramer44** [comment]
I'm going to close this for now, since this no longer seems necessary. @manthanhd Feel free to open again if this is still a blocker for you.
