### ISSUE TITLE
Resolution problem?

### ISSUE THREAD

**Issue by Smilestate** [XRPLF/xrpl4j#155]
When I use xrplclient.transaction, the following happens! The following is a code example:
```java
TransactionRequestParams of = TransactionRequestParams.of(Hash256.of("0587EB50ADBA0FFE50B41D1EAB5569199DAF59429F7964CB6BB0F0B1E519C0B6"));
TransactionResult<?> transactions = xrplClient.transaction(of, Transaction.class);

Error: No matching AccountSetFlag enum value for int value SetFee
```
When I checked your source code, I found that TransactionType.class does not have the keyword SetFee.
The enumeration is attached as follows:
```java
public enum TransactionType {
    ACCOUNT_SET("AccountSet"),
    ACCOUNT_DELETE("AccountDelete"),
    CHECK_CANCEL("CheckCancel"),
    CHECK_CASH("CheckCash"),
    CHECK_CREATE("CheckCreate"),
    DEPOSIT_PRE_AUTH("DepositPreauth"),
    ESCROW_CANCEL("EscrowCancel"),
    ESCROW_CREATE("EscrowCreate"),
    ESCROW_FINISH("EscrowFinish"),
    OFFER_CANCEL("OfferCancel"),
    OFFER_CREATE("OfferCreate"),
    PAYMENT("Payment"),
    PAYMENT_CHANNEL_CLAIM("PaymentChannelClaim"),
    PAYMENT_CHANNEL_CREATE("PaymentChannelCreate"),
    PAYMENT_CHANNEL_FUND("PaymentChannelFund"),
    SET_REGULAR_KEY("SetRegularKey"),
    SIGNER_LIST_SET("SignerListSet"),
    TRUST_SET("TrustSet");
}
Error: Not Found SetFee. 
```
Please check the xrpl scan: https://livenet.xrpl.org/transactions/C421D3377A5A702361DD075F2AC3A37AC29F9B238A1C28C8C56DC75281650CB2/raw

**Comment by nkramer44** [comment]
Currently, xrpl4j doesn't support any pseudo-transactions (such as `SetFee`).  When trying to deserialize that `SetFee` transaction to a `Transaction`, Jackson will fail, since we have not defined the `SetFee` transaction yet. 

The error message `No matching AccountSetFlag enum value for int value SetFee` is definitely misleading. It looks like that error message was copy pasted from another enum with a similar method. I will create a ticket to fix that message.

I don't think we have any plans to support pseudo-transactions, but if you really need them maybe we can prioritize adding them.

**Comment by Smilestate** [comment]
My current approach is to ignore the error.So what are the pseudo-transactions that I can exclude! Prevent the program from reporting errors!

**Comment by nkramer44** [comment]
On second thought, I actually think it would be valuable to include pseudo transaction mappings in xrpl4j. While users that use the library to submit transactions won't need them, I don't think we should force developers to swallow errors when reading from a ledger that has a pseudo transaction. 

I've created #159 and #158 to track this work. For now, you can just ignore the error, but in v2.2.0 these errors shouldn't occur.
