### ISSUE TITLE
Add Pseudo-transaction mappings

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#158]
We should add `Transaction` subclasses for all [pseudo-transactions](https://xrpl.org/pseudo-transaction-types.html). Even though developers will never want to sign and submit their own pseudo-transactions, if they try to retrieve a pseudo-transaction from the ledger, xrpl4j will blow up.

**Comment by sappenin** [comment]
For future information, there's a bug in rippled with certain pseudo-transactions that would require an ammendment to fix, but that don't _really_ matter. However, they will unexpectedly break certain deserializers, so we need to be cognizant.

Note that there is a bug in rippled (that is unlikely to be fixed due to requiring an ammendment and the fact that the impact is very low). For example, it looks like the `account` is encoded as `0000000000000000000000000000000000000000` in e.g. `SetFee` but is omitted in the `UNLModify` encoding from rippled (this is a bug). 

For a full example, SetFee is encoded as 

```
12006524000000002603F62301201E0000000A201F00989680202
0001E848035000000000000000A6840000000000000007300811
40000000000000000000000000000000000000000
``` 

and `UNLModify` is encoded as ```
120066240000000026040B5200684000000000000000730070132
1EDB6FC8E803EE8EDC2793F1EC917B2EE41D35255618DEB91D3F9
B1FC89B75D4539810000101101```

(ripple-binary-codec has an extra 40 0s because it's assuming it's supposed to do the same thing as SetFee).

**Comment by nkramer44** [comment]
Also for future information, I don't believe the thing that will blow up here is the `XrplBinaryCodec` class. We force users to ask for transactions from rippled with the `binary` flag == `false`. This way, rippled returns transactions in JSON form, not binary, and we can just let Jackson deserialize the JSON for us.

In our case, Jackson will be the thing to blow up because when it goes to create a `Transaction` and no `Account` field exists, `Transaction` will throw an error.

Likely, we'll need to do some magic in `TransactionDeserializer` to handle this edge case once we introduce pseudo transactions.
