### ISSUE TITLE
Need to Make Destination Tag to be Unsigned Long

### ISSUE THREAD

**Issue by txysystems** [XRPLF/xrpl4j#341]
Hello. I'm a developer and a big fan of ripple. If you will belief me, IT IS THE BEST CRYPTOCURRENCY FOR ME.
My issue is that, I'm working on developing a ripple wallet, using the official java library (xrpl4j), but I realize that most of the crypto exchange platforms uses destination tags higher than the maximum value of UnsignedInteger specified in the api.
To overcome this limitation, I hereby plead that THE DESTINATION TAG VARIABLE TYPE SHOULD BE CHANGED FROM UNSIGNEDINTEGER TO UNSIGNEDLONG.
Thanks in anticipation of a relieving response.
Love you all.

**Comment by nkramer44** [comment]
Hi @txysystems, I'm not aware of any exchanges that use destination tags larger than a 32-bit unsigned integer. In fact, I'm not sure how that would be possible, considering the XRPL protocol enforces that destination and source tags are 32-bit unsigned integers. the `UnsignedInteger` class represents a 32-bit unsigned integer, so should be large enough to hold any destination tag. 

Can you tell me which on which exchange specifically you are seeing these larger destination tags?

**Comment by sappenin** [comment]
Closing this as `wont-fix` since `UnsignedInteger` holds unsigned integers up to 2^32-1 (i.e., that can fit into 32-bits), and per the docs [here](https://xrpl.org/source-and-destination-tags.html):

> In transactions, both source and destination tags are formatted as 32-bit unsigned integers.

You can also see in transactions (e.g., a [Payment](https://xrpl.org/payment.html)) that destination tags are typed as `UInt32`.

Please re-open or make a comment here if there's still a concern.
