### ISSUE TITLE
Make default flags value be `0` instead of `tfFullyCanonicalSig`

### ISSUE THREAD

**Issue by sappenin** [XRPLF/xrpl4j#424]
The default value for `Payment.flags()` is just a set of flags where only the `tfFullyCanonicalSig` flag is set. That happens to be 0x80000000 (highest bit is 1, all others are 0), which also happens to be `Integer.MAX_VALUE` (See [here](https://xrpl.org/transaction-common-fields.html#global-flags) for more details).

However, `tfFullyCanonicalSig` was deprecated, and is no longer honored by rippled (see [here](https://xrpl.org/transaction-common-fields.html#global-flags)).

This relates to #32 and #TODO.

**Comment by nkramer44** [comment]
This might not be necessary. The real issue is that we don't support "empty" flags. This is an issue because of the following scenario, even if we default to zero:
1) xrpl4j decodes a (valid) binary blob that _does not_ contain a `Flags` field. 
2) This results in a `Transaction` where `flags() == 0` because we will now default to zero.
3) xrpl4j encodes that `Transaction` to binary
4) The encoded binary will not be the same as the original binary

Therefore, we should close this ticket in favor of #425

**Comment by sappenin** [comment]
Agreed!
