### ISSUE TITLE
sync data occur error at height 90150378

### ISSUE THREAD

**Issue by SomerGG** [XRPLF/xrpl4j#546]
When I sync a block transactions, I get the following error：
```
org.xrpl.xrpl4j.client.JsonRpcClientErrorException: com.fasterxml.jackson.databind.JsonMappingException: value (-1) is outside the range for an unsigned long value (through reference chain: org.xrpl.xrpl4j.model.transactions.ImmutableTransactionMetadata$Json[\"delivered_amount\"]) (through reference chain: org.xrpl.xrpl4j.model.client.ledger.ImmutableLedgerResult$Json[\"ledger\"]->org.xrpl.xrpl4j.model.ledger.ImmutableLedgerHeader$Json[\"transactions\"]->java.util.ArrayList[81])
```
my xrpl4j version：
```
<dependency>
    <groupId>org.xrpl</groupId>
    <artifactId>xrpl4j-client</artifactId>
    <version>3.4.0</version>
</dependency>
<dependency>
    <groupId>org.xrpl</groupId>
    <artifactId>xrpl4j-core</artifactId>
    <version>3.4.0</version>
</dependency>
```

The rpcUrl：
```
https://s1.ripple.com:51234/
```

the error occur block number such as：
- 90150378
- 90156059

**Comment by imnotanoob** [comment]
It looks like there is a bug that delivered amount is negative. (https://xrpscan.com/tx/D540F1E21A145F5CC9B95BEEF142A766C83E76E09A0E1DA6C2C2027FA7DB2B22)

A delivered amount should never be negative unless the amount itself was 0.

**Comment by sappenin** [comment]
Hi @SomerGG -- thanks for reporting this issue. 

There are two things going on in this issue, so I'll try to disambiguate.

First, this is indeed a bug in rippled that was identified several months ago, and has been addressed via the [fixAMMv1_1](https://livenet.xrpl.org/amendment/35291ADD2D79EB6991343BDA0912269C817D0F094B02226C1C14AD2858962ED4) amendment. This fix amendment is currently being voted upon, and pending the governance votes of the UNL could activate at any time.

However, because that amendment hasn't yet activated, this is creating historical data issues in xrpl4j. To mitigate that, I've been working on https://github.com/XRPLF/xrpl4j/pull/535. I don't have a firm release date for that just yet, but am hoping for something by the end of this week.

I'll post more here once I have more progress on the library fix.

**Comment by sappenin** [comment]
This has been fixed via https://github.com/XRPLF/xrpl4j/pull/535. Please upgrade to v3.5.0 or above.
