### ISSUE TITLE
Add validation to LedgerIndex

### ISSUE THREAD

**Issue by nkramer44** [XRPLF/xrpl4j#93]
`LedgerIndex` is just a wrapper around `String`. There are three defined character `String`s that are recognized by rippled as shortcuts: `"validated"`, `"current"`, and `"closed"`.  All other ledger indexes must be a numerical `String` like `"12345"`. 

Currently, we don't do any client side validation that the `String` wrapped by `LedgerIndex` is either one of the shortcut Strings or a number, so a user could technically construct a `LedgerIndex` wrapping `"foo"`.  While this will ultimately be caught by rippled, we should add validation in the `LedgerIndex` class to short circuit any errors.

**Comment by tekbar11** [comment]
Hi. This doesn't seem very difficult. I'd like to work on this issue if it's okay.

**Comment by sappenin** [comment]
@tekbar11 thanks, and that sounds great! I'll assign this task to you. I think the only outstanding question in my mind is, "what should happen if someone does: `LedgerIndex.of("foo")`? If an exception should be thrown, which kinds?

@nkramer44 @nhartner for input here too.

**Comment by tekbar11** [comment]
Thanks @sappenin for assigning me to this. In my opinion, the `LedgerIndex` factory should throw an IllegalArgumentException, but tests seem to expect a NumberFormatException in all cases.

I would also like to create a nested *enum* to represent shortcut values (for modularity's sake and easy iteration on possible values), but maybe this is overkill? I have no idea if you plan to add more shortcuts.

Also, shouldn't the constructor be private, since there is a public factory method?

**Comment by sappenin** [comment]
> Also, shouldn't the constructor be private, since there is a public factory method?

This seems fined to me, but it would be a potentially breaking change, so maybe let's just mark the public constructor as `@Deprecated` with a Javadoc comment that it will be removed in a future version?

**Comment by tekbar11** [comment]
Hi, since my pull request has been merged, shouldn't this issue be considered as fixed? Thanks.

**Comment by sappenin** [comment]
Yes, thanks for pointing this out. This is fixed via #98
